Don't install outdated kubernetes lib on Windows/macOS
... because for some reason the installation of one of its dependencies
fails there:

Collecting websocket-client<=0.40.0,>=0.32.0 (from kubernetes==3.0.0->saltext.kubernetes==0.1.dev3+gb38d4fd)
  Downloading websocket_client-0.40.0.tar.gz (196 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.